
apiVersion: v1
kind: Pod
metadata:
  name: sonarqube-stack
spec:
  containers:
    - name: db
      image: postgres:15-alpine
      env:
        - name: POSTGRES_USER
          value: sonar
        - name: POSTGRES_PASSWORD
          value: sonar
        - name: POSTGRES_DB
          value: sonar
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data

    - name: sonarqube
      image: sonarqube:community
      ports:
        - containerPort: 9000
          hostPort: 9000
      env:
        - name: SONAR_JDBC_URL
          value: jdbc:postgresql://localhost:5432/sonar
        - name: SONAR_JDBC_USERNAME
          value: sonar
        - name: SONAR_JDBC_PASSWORD
          value: sonar
      volumeMounts:
        - name: sonarqube-data
          mountPath: /opt/sonarqube/data
        - name: sonarqube-extensions
          mountPath: /opt/sonarqube/extensions

  volumes:
    - name: postgres-data
      emptyDir: {}
    - name: sonarqube-data
      emptyDir: {}
    - name: sonarqube-extensions
      emptyDir: {}
